### ISSUE TITLE
Best way of verifying if a repo was already clone?

### ISSUE THREAD

**Issue by Macarse** [tuvistavie/elixir-git-cli#4]
Hey!

I started using this lib and I am not very fluent with elixir yet.
Which is the best way to implement "if it's not already cloned, clone it"

`File.exists?("./repository")`?

**Comment by tuvistavie** [comment]
Hi!
I suppose this should be enough for most cases.
If you want to handle cases where the directory exists but is not a valid git repository, you could either check for `./repository/.git`, or even try to run `git status` or something and check for the result. 

For example:

```elixir
repo = %Git.Repository{path: path}
case Git.status(repo) do
  {:ok, _} -> "no problem"
  {:error, _} -> "repo is corrupted, or something"
end
```

**Comment by Macarse** [comment]
Thanks for your answer!
